name: Tag Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to tag this release to"
        required: true
        default: "1"

defaults:
  run:
    shell: bash

jobs:
  create-release-tag:
    name: Create release tag
    runs-on: ubuntu-latest
    steps:
      # Need to use a PAT or follow-on actions are not triggered
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
      - name: Set git username and email
        run: |
          git config --global user.name "$(git log -n1 --pretty=format:%an)"
          git config --global user.email "$(git log -n1 --pretty=format:%ae)"
      - name: Tag release
        run: |
          version='${{ github.event.inputs.version }}'
          tag="v${version}"
          git tag "$tag" --annotate --message="Release $tag"
          git push origin "$tag"
        